#!/bin/bash

# Realización de Jonás A. Reyes C. | jonasreyes@yandex.com
# Octubre 2022
# Tienes derecho a copiar, modificar, distribuir, etc. 
# No olvides mencionar la fuente originaria del script:
# https://github.com/jonasreyes

# Requerimientos y Dependencias:
# Debes tener instalado Laravel y AWK (por defecto en GNU/Linux)
# Debes ejecutar este script desde la carpeta principal de tu Proyecto Laravel

# Verificando que tengas instalados los paquetes necesarios
## . check_laravel_dependences.sh (Este script estaba separado 
## pero para mantener la facilidad he decidido mantenerlo en un solo archivo)
EPHP=$(php -v 2>/dev/null | awk '{print $2; exit}')
ECOMPOSER=$(composer --version 2>/dev/null | awk '{print $3; exit}')
EMYSQL=$(mysql --version 2>/dev/null | awk '{print $3}')
EXAMPP=$(xampp version 2>/dev/null | awk '{print $5}')
ESQLITE=$(sqlite3 --version 2>/dev/null | awk '{print $1}')
ELARAVEL=$(laravel --version 2>/dev/null | awk '{print $3}')
EDOCKER=$(docker --version 2>/dev/null | awk '{print $3}')
EDOCKER_COMPOSE=$(docker-compose --version 2>/dev/null | awk '{print $4}')

# Cabecera del Programa (impresión)
cat << EOF

----------------------------
  SCRIPT LARAVELSERVE 1.0
  Autor: Jonas A. Reyes C.
----------------------------

EOF

# Chequearemos primeramente si el sistema del usuario cuenta con Docker y Docker-compose
# para correr proyectos con Laravel Sail
if [ -z $EDOCKER ]; then
  echo "----------------------------"
  echo "  No se ha detectado Docker en su sistema, por lo que no podrá usar Laravel Sail hasta instalarlo."
  echo "----------------------------"
  EDOCKER="No Detectado."
else
  if [ -z $EDOCKER_COMPOSE ]; then
      echo "----------------------------"
      echo "  Tiene instalado Docker en su sistema, sin embargo para poder usar Laravel Sail"
      echo "  precisa instalar 'docker-compose'."
      echo "----------------------------"
    EDOCKER_COMPOSE="No detectado."
  fi
fi

if [ -z $EPHP ]
then
  echo "    No se encuentra PHP instalado de forma nativa, procederemos a buscar si tiene Xampp en su sistema."
    if [ -z $EXAMPP ]; then
      echo "----------------------------"
      echo "  No se encuentra XAMPP instalado en su sistema. No puedes continuar."
      echo "----------------------------"
      exit 1
    fi
else
    # En caso de que el usuario cuente con PHP instalado,
    # procedemos a verificar si cuenta con Bases de Datos.
    # la ausencia de Basese de Datos no tiene que significar
    # la interrupción del arranque del servidor, puesto que
    # puede suceder que el usuario tenga un proyecto LARAVEL
    # que no requiera BBDD. En todo caso se informa al usuario.
    if [ -z $EMYSQL ]; then

      echo "----------------------------"
      echo "  Adevertencia: No se ha detectado MySQL en su sistema, sin embargo puedes continuar."
      echo "----------------------------"

      EMYSQL="No detectado."
    fi

    if [ -z $ESQLITE ]; then
      echo "----------------------------"
      echo "  Adevertencia: No se encuentra SQLite3 instalado en su sistema."
      echo "----------------------------"

      ESQLITE="No detectado."
    fi
fi

# Si el script llega a este punto sabremos que el usuario tiene 
# como mínimo instalado PHP en su sistema.
# Procedemos a verificar que tenga instalado composer en su sistema.
if [ -z $ECOMPOSER ]; then
      echo "----------------------------"
      echo "  No se encuentra Composer instalado en su sistema. Para poder continuar debes instalarlo."
      echo "----------------------------"
  exit 1
fi

if [ -z $ELARAVEL ]; then
  echo "No se encuentra instalado de manera global en su sistema Laravel Installer,"
  echo "sin embargo puede instalar un proyecto Laravel mediante la instrucción:"
  echo '-->> "composer create-projetc laravel/laravel app-de-ejemplo" <<--'
  echo "Para instalar Laravel Installer de manera Global en su sistema ejecute la siguiente instrucción:" 
  echo '-->> "composer global require laravel/installer" <<--' 
  ELARAVEL="No detectado."
fi

# Listamos las versiones de los paquetes dependencias de Laravel
# que sí se encuentran instalados en el sistema de usuario.
cat << EOF

----------------------------
  Versión de PHP: $EPHP
  Versión de Composer: $ECOMPOSER
  Versión de MySQL: $EMYSQL
  Versión de XAMPP: $EXAMPP
  Versión de SQLite: $ESQLITE
  Versión de Laravel: $ELARAVEL
  Versión de Docker: $EDOCKER
  Versión de Docker-Compose: $EDOCKER_COMPOSE

----------------------------

EOF
### Fin del contenido que antes tenía separado en el script 'check_laravel_dependences'


### Arrancando el Servidor si todo está correcto hasta este punto.
#Verificando que se esté ejecutando el Script desde el interior de un proyecto Laravel
if [ -f './composer.json' ]; then
  echo "----------------------------"
  echo "  Ejecutando LaravelServe desde el interior de un proyecto Laravel."
  echo "----------------------------"
  if [ -f './vendor/bin/sail' ]; then
    echo "----------------------------"
    echo "  Su proyecto Laravel tiene instalado el servicio Sail."
    echo "  Si lo desea puede arrancar su proyecto Laravel Sail y luego ejecute LaravelServe"
    echo "  para que tenga ambos servicios funcionando al mismo tiempo. Es útil cuando requiere"
    echo "  del uso de Sail para levantar un servicio de Base de Datos que no esté instalado de"
    echo "  forma nativa en su sistema."
    # ESAIL=$(./vendor/bin/sail up &)
    echo "----------------------------"
  fi
else
  echo "----------------------------"
  echo "  Error: Para continuar debe ejecutar LaraveServe desde el interior de un proyecto Laravel."
  echo "----------------------------"
  exit 1
fi

# Seleccionamos la interfaz de red de la que queremos obtener la IP
LPORT="8000"
INTERFACE='wlp2s0'

# Obtenemos la dirección IP
MYIP=$(ifconfig $INTERFACE | grep 'inet' | awk  '{print $2; exit}')

# Armamos la IP para la app Laravel
MY_LARAVEL_SERVE="$MYIP:$LPORT"

# Imprimimos la ip obtenida!
  echo "----------------------------"
  echo "  Tu proyecto Laravel estará accesible para tu Red Local en: $MY_LARAVEL_SERVE" 
  echo "----------------------------"

# Comando Laravel
php artisan serve --host=$MY_LARAVEL_SERVE
